package hashtag.generator.hashapplication.ModelClasses;

/**
 * Created by cuneytcarikci on 29/07/16.
 */
public class Constants {

    /**
     * list from:
     *  https://gist.github.com/Keeguon/2310008
     */
    public static final String COUNTRIES = "[ \n" +
            "{\"name\": \"birthday\", \"code\": \"AF\"}, \n" +
            "{\"name\": \"celebrate\", \"code\": \"AX\"}, \n" +
            "{\"name\": \"cakes\", \"code\": \"AL\"}, \n" +
            "{\"name\": \"giftideas\", \"code\": \"DZ\"}, \n" +
            "{\"name\": \"birthdaymonth\", \"code\": \"AS\"}, \n" +
            "{\"name\": \"birthdayweek\", \"code\": \"AD\"}, \n" +
            "{\"name\": \"fashion\", \"code\": \"AO\"}, \n" +
            "{\"name\": \"lovewins\", \"code\": \"AI\"}, \n" +
            "{\"name\": \"loveyourbody\", \"code\": \"AQ\"}, \n" +
            "{\"name\": \"lovelife\", \"code\": \"AG\"}, \n" +
            "{\"name\": \"foodie\", \"code\": \"AR\"}, \n" +
            "{\"name\": \"foodiepics\", \"code\": \"AM\"}, \n" +
            "{\"name\": \"dessert\", \"code\": \"AW\"}, \n" +
            "{\"name\": \"foodieblogger\", \"code\": \"AU\"}, \n" +
            "{\"name\": \"coffeelover\", \"code\": \"AT\"}, \n" +
            "{\"name\": \"Azerbaijan\", \"code\": \"AZ\"}, \n" +
            "{\"name\": \"coffeeaddict\", \"code\": \"BS\"}, \n" +
            "{\"name\": \"coffeelovers\", \"code\": \"BH\"}, \n" +
            "{\"name\": \"baristalife\", \"code\": \"BD\"}, \n" +
            "{\"name\": \"coffeeshopvibes\", \"code\": \"BB\"}, \n" +
            "{\"name\": \"coffeeholic\", \"code\": \"BY\"}, \n" +
            "{\"name\": \"coffeeculture\", \"code\": \"BE\"}, \n" +
            "{\"name\": \"morningvibes\", \"code\": \"BZ\"}, \n" +
            "{\"name\": \"morningglory\", \"code\": \"BJ\"}, \n" +
            "{\"name\": \"morningselfie\", \"code\": \"BM\"}, \n" +
            "{\"name\": \"morningroutine\", \"code\": \"BT\"}, \n" +
            "{\"name\": \"morningworkout\", \"code\": \"BO\"}, \n" +
            "{\"name\": \"landscape\", \"code\": \"BA\"}, \n" +
            "{\"name\": \"sunsetpics\", \"code\": \"BW\"}, \n" +
            "{\"name\": \"sunsetgram\", \"code\": \"BV\"}, \n" +
            "{\"name\": \"sunsetlove\", \"code\": \"BR\"}, \n" +
            "{\"name\": \"motivation\", \"code\": \"IO\"}, \n" +
            "{\"name\": \"workfromhome\", \"code\": \"BN\"}, \n" +
            "{\"name\": \"workingmom\", \"code\": \"BG\"}, \n" +
            "{\"name\": \"workspace\", \"code\": \"BF\"}, \n" +
            "{\"name\": \"workinprogress\", \"code\": \"BI\"}, \n" +
            "{\"name\": \"workworkwork\", \"code\": \"KH\"}, \n" +
            "{\"name\": \"travelgram\", \"code\": \"CM\"}, \n" +
            "{\"name\": \"vacation\", \"code\": \"CA\"}, \n" +
            "{\"name\": \"holidayshopping\", \"code\": \"CV\"}, \n" +
            "{\"name\": \"holidaymode\", \"code\": \"KY\"}, \n" +
            "{\"name\": \"bookblogger\", \"code\": \"CF\"}, \n" +
            "{\"name\": \"bookcommunity\", \"code\": \"TD\"}, \n" +
            "{\"name\": \"bookworm\", \"code\": \"CL\"}, \n" +
            "{\"name\": \"bookstagrammer\", \"code\": \"CN\"}, \n" +
            "{\"name\": \"bookaholic\", \"code\": \"CX\"}, \n" +
            "{\"name\": \"bookphotography\", \"code\": \"CC\"}, \n" +
            "{\"name\": \"bookshelve\", \"code\": \"CO\"}, \n" +
            "{\"name\": \"bookreview\", \"code\": \"KM\"}, \n" +
            "{\"name\": \"socialwork\", \"code\": \"CG\"}, \n" +
            "{\"name\": \"mentalhealth\", \"code\": \"CD\"}, \n" +
            "{\"name\": \"fundraising\", \"code\": \"CK\"}, \n" +
            "{\"name\": \"helpingothers\", \"code\": \"CR\"}, \n" +
            "{\"name\": \"charity\", \"code\": \"CI\"}, \n" +
            "{\"name\": \"streetphotography\", \"code\": \"HR\"}, \n" +
            "{\"name\": \"nightphotography\", \"code\": \"CU\"}, \n" +
            "{\"name\": \"moonphotography\", \"code\": \"CY\"}, \n" +
            "{\"name\": \"nightowl\", \"code\": \"CZ\"}, \n" +
            "{\"name\": \"happiness\", \"code\": \"DK\"}, \n" +
            "{\"name\": \"motivationalquotes\", \"code\": \"DJ\"}, \n" +
            "{\"name\": \"entrepreneur\", \"code\": \"DM\"}, \n" +
            "{\"name\": \"happinesstherapy\", \"code\": \"DO\"}, \n" +
            "{\"name\": \"happinessproject\", \"code\": \"EC\"}, \n" +
            "{\"name\": \"aesthetic\", \"code\": \"EG\"}, \n" +
            "{\"name\": \"depression\", \"code\": \"SV\"}, \n" +
            "{\"name\": \"heartbroken\", \"code\": \"GQ\"}, \n" +
            "{\"name\": \"sadquotes\", \"code\": \"ER\"}, \n" +
            "{\"name\": \"artistsoninstagram\", \"code\": \"EE\"}, \n" +
            "{\"name\": \"artstagram\", \"code\": \"ET\"}, \n" +
            "{\"name\": \"contemporaryart\", \"code\": \"FK\"}, \n" +
            "{\"name\": \"artstudio\", \"code\": \"FO\"}, \n" +
            "{\"name\": \"artworks\", \"code\": \"FJ\"}, \n" +
            "{\"name\": \"schoolmemories\", \"code\": \"FI\"}, \n" +
            "{\"name\": \"backbenchers\", \"code\": \"FR\"}, \n" +
            "{\"name\": \"schoolfriends\", \"code\": \"GF\"}, \n" +
            "{\"name\": \"schoollifefun\", \"code\": \"PF\"}, \n" +
            "{\"name\": \"travelblogger\", \"code\": \"TF\"}, \n" +
            "{\"name\": \"travelholic\", \"code\": \"GA\"}, \n" +
            "{\"name\": \"travelgram\", \"code\": \"GM\"}, \n" +
            "{\"name\": \"traveltheworld \", \"code\": \"GE\"}, \n" +
            "{\"name\": \"photographytips\", \"code\": \"DE\"}, \n" +
            "{\"name\": \"winterscoming\", \"code\": \"GH\"}, \n" +
            "{\"name\": \"winterfashion\", \"code\": \"GI\"}, \n" +
            "{\"name\": \"winteroutfit\", \"code\": \"GR\"}, \n" +
            "{\"name\": \"summeriscoming\", \"code\": \"GL\"}, \n" +
            "{\"name\": \"summervacation \", \"code\": \"GD\"}, \n" +
            "{\"name\": \"summeroutfit\", \"code\": \"GP\"}, \n" +
            "{\"name\": \"fashionista\", \"code\": \"GU\"}, \n" +
            "{\"name\": \"fashionblog\", \"code\": \"GT\"}, \n" +
            "{\"name\": \"fashionblogger\", \"code\": \"GG\"}, \n" +
            "{\"name\": \"fashiontrends\", \"code\": \"GN\"}, \n" +
            "{\"name\": \"natureisamazing\", \"code\": \"GW\"}, \n" +
            "{\"name\": \"natureatitsbest \", \"code\": \"GY\"}, \n" +
            "{\"name\": \"picoftheday\", \"code\": \"HT\"}, \n" +
            "{\"name\": \"photoshoot\", \"code\": \"HM\"}, \n" +
            "{\"name\": \"styleinfluencer\", \"code\": \"VA\"}, \n" +
            "{\"name\": \"styleicon\", \"code\": \"HN\"}, \n" +
            "{\"name\": \"styleaddict\", \"code\": \"HK\"}, \n" +
            "{\"name\": \"styleinspo\", \"code\": \"HU\"}, \n" +
            "{\"name\": \"instalike\", \"code\": \"IS\"}, \n" +
            "{\"name\": \"followforfollow\", \"code\": \"IN\"}, \n" +
            "{\"name\": \"selfie\", \"code\": \"ID\"}, \n" +
            "{\"name\": \"selfiemode\", \"code\": \"IR\"}, \n" +
            "{\"name\": \"selfiegamestrong\", \"code\": \"IQ\"}, \n" +
            "{\"name\": \"selfielover\", \"code\": \"IE\"}, \n" +
            "{\"name\": \"instalikes\", \"code\": \"IM\"}, \n" +
            "{\"name\": \"girlpower\", \"code\": \"IL\"}, \n" +
            "{\"name\": \"girlsthatlift\", \"code\": \"IT\"}, \n" +
            "{\"name\": \"girlsnightout \", \"code\": \"JM\"}, \n" +
            "{\"name\": \"friends\", \"code\": \"JP\"}, \n" +
            "{\"name\": \"friends4ever\", \"code\": \"JE\"}, \n" +
            "{\"name\": \"friendsforkeeps\", \"code\": \"JO\"}, \n" +
            "{\"name\": \"friendshipbracelets \", \"code\": \"KZ\"}, \n" +
            "{\"name\": \"friendshipquotes\", \"code\": \"KE\"}, \n" +
            "{\"name\": \"photography\", \"code\": \"KI\"}, \n" +
            "{\"name\": \"portraitphotography\", \"code\": \"KP\"}, \n" +
            "{\"name\": \"photoblog\", \"code\": \"KR\"}, \n" +
            "{\"name\": \"photogrid\", \"code\": \"KW\"}, \n" +
            "{\"name\": \"familytime\", \"code\": \"KG\"}, \n" +
            "{\"name\": \"familygoals\", \"code\": \"LA\"}, \n" +
            "{\"name\": \"familypic\", \"code\": \"LV\"}, \n" +
            "{\"name\": \"familyholiday\", \"code\": \"LB\"}, \n" +
            "{\"name\": \"lifeisgood\", \"code\": \"LS\"}, \n" +
            "{\"name\": \"makeuplover\", \"code\": \"LR\"}, \n" +
            "{\"name\": \"makeupgoals\", \"code\": \"LY\"}, \n" +
            "{\"name\": \"makeupaddict\", \"code\": \"LI\"}, \n" +
            "{\"name\": \"makeuptutorial\", \"code\": \"LT\"}, \n" +
            "{\"name\": \"makeupobsession\", \"code\": \"LU\"}, \n" +
            "{\"name\": \"makeupblogger\", \"code\": \"MO\"}, \n" +
            "{\"name\": \"nofilter\", \"code\": \"MK\"}, \n" +
            "{\"name\": \"nofilterselfie\", \"code\": \"MG\"}, \n" +
            "{\"name\": \"swag\", \"code\": \"MW\"}, \n" +
            "{\"name\": \"nofilterfriday\", \"code\": \"MY\"}, \n" +
            "{\"name\": \"nofiltersneeded\", \"code\": \"MV\"}, \n" +
            "{\"name\": \"beach\", \"code\": \"ML\"}, \n" +
            "{\"name\": \"fitness\", \"code\": \"MT\"}, \n" +
            "{\"name\": \"beachday\", \"code\": \"MH\"}, \n" +
            "{\"name\": \"surfing\", \"code\": \"MQ\"}, \n" +
            "{\"name\": \"wanderlust\", \"code\": \"MR\"}, \n" +
            "{\"name\": \"beachwaves\", \"code\": \"MU\"}, \n" +
            "{\"name\": \"beachwedding\", \"code\": \"YT\"}, \n" +
            "{\"name\": \"beachview\", \"code\": \"MX\"}, \n" +
            "{\"name\": \"handmadewithlove\", \"code\": \"FM\"}, \n" +
            "{\"name\": \"handmadegifts\", \"code\": \"MD\"}, \n" +
            "{\"name\": \"handmadeearrings\", \"code\": \"MC\"}, \n" +
            "{\"name\": \"handmadesoap\", \"code\": \"MN\"}, \n" +
            "{\"name\": \"handmadecards\", \"code\": \"MS\"}, \n" +
            "{\"name\": \"sketchbook\", \"code\": \"MA\"}, \n" +
            "{\"name\": \"abstractart\", \"code\": \"MZ\"}, \n" +
            "{\"name\": \"artoftheday\", \"code\": \"MM\"}, \n" +
            "{\"name\": \"artistic\", \"code\": \"NA\"}, \n" +
            "{\"name\": \"artistsoninstagram\", \"code\": \"NR\"}, \n" +
            "{\"name\": \"artisticmakeup\", \"code\": \"NP\"}, \n" +
            "{\"name\": \"funny\", \"code\": \"NL\"}, \n" +
            "{\"name\": \"memes\", \"code\": \"AN\"}, \n" +
            "{\"name\": \"humor\", \"code\": \"NC\"}, \n" +
            "{\"name\": \"funnyfaces\", \"code\": \"NZ\"}, \n" +
            "{\"name\": \"flowers\", \"code\": \"NI\"}, \n" +
            "{\"name\": \"homedecor\", \"code\": \"NE\"}, \n" +
            "{\"name\": \"flowersphotography \", \"code\": \"NG\"}, \n" +
            "{\"name\": \"flowerlovers\", \"code\": \"NU\"}, \n" +
            "{\"name\": \"flowersmakemehappy\", \"code\": \"NF\"}, \n" +
            "{\"name\": \"weddingphotography\", \"code\": \"MP\"}, \n" +
            "{\"name\": \"instawedding\", \"code\": \"NO\"}, \n" +
            "{\"name\": \"bridetobe\", \"code\": \"OM\"}, \n" +
            "{\"name\": \"weddingflowers\", \"code\": \"PK\"}, \n" +
            "{\"name\": \"weddingring\", \"code\": \"PW\"}, \n" +
            "{\"name\": \"weddingdress\", \"code\": \"PS\"}, \n" +
            "{\"name\": \"bestoftheday\", \"code\": \"PA\"}, \n" +
            "{\"name\": \"gym\", \"code\": \"PG\"}, \n" +
            "{\"name\": \"fitnessmotivation\", \"code\": \"PY\"}, \n" +
            "{\"name\": \"weightloss\", \"code\": \"PE\"}, \n" +
            "{\"name\": \"bodybuilder\", \"code\": \"PH\"}, \n" +
            "{\"name\": \"gymlover\", \"code\": \"PN\"}, \n" +
            "{\"name\": \"gymaholic\", \"code\": \"PL\"}, \n" +
            "{\"name\": \"gymfreak\", \"code\": \"PT\"}, \n" +
            "{\"name\": \"baby\", \"code\": \"PR\"}, \n" +
            "{\"name\": \"motherhood\", \"code\": \"QA\"}, \n" +
            "{\"name\": \"babyclothes\", \"code\": \"RE\"}, \n" +
            "{\"name\": \"babyfever\", \"code\": \"RO\"}, \n" +
            "{\"name\": \"babycare\", \"code\": \"RU\"}, \n" +
            "{\"name\": \"babyshop\", \"code\": \"RW\"}, \n" +
            "{\"name\": \"inspirationquotes\", \"code\": \"SH\"}, \n" +
            "{\"name\": \"inspirationalthoughts\", \"code\": \"KN\"}, \n" +
            "{\"name\": \"inspirationalspeaker\", \"code\": \"LC\"}, \n" +
            "{\"name\": \"memer\", \"code\": \"PM\"}, \n" +
            "{\"name\": \"memestagram\", \"code\": \"VC\"}, \n" +
            "{\"name\": \"lol\", \"code\": \"WS\"}, \n" +
            "{\"name\": \"joke\", \"code\": \"SM\"}, \n" +
            "{\"name\": \"lmao\", \"code\": \"ST\"}, \n" +
            "{\"name\": \"yummy\", \"code\": \"SA\"}, \n" +
            "{\"name\": \"yummyintummy\", \"code\": \"SN\"}, \n" +
            "{\"name\": \"pizza\", \"code\": \"CS\"}, \n" +
            "{\"name\": \"foodlover\", \"code\": \"SC\"}, \n" +
            "{\"name\": \"foodblogger\", \"code\": \"SL\"}, \n" +
            "{\"name\": \"party\", \"code\": \"SG\"}, \n" +
            "{\"name\": \"fun\", \"code\": \"SK\"}, \n" +
            "{\"name\": \"friends\", \"code\": \"SI\"}, \n" +
            "{\"name\": \"partywear\", \"code\": \"SB\"}, \n" +
            "{\"name\": \"partydecorations\", \"code\": \"SO\"}, \n" +
            "{\"name\": \"partyoutfit\", \"code\": \"ZA\"}, \n" +
            "{\"name\": \"partysupplies\", \"code\": \"GS\"}, \n" +
            "{\"name\": \"homesweethome\", \"code\": \"ES\"}, \n" +
            "{\"name\": \"vintage\", \"code\": \"LK\"}, \n" +
            "{\"name\": \"homeinterior\", \"code\": \"SD\"}, \n" +
            "{\"name\": \"healthylifestyles\", \"code\": \"SR\"}, \n" +
            "{\"name\": \"healthybodyhealthymind\", \"code\": \"SJ\"}, \n" +
            "{\"name\": \"blackandwhitepics\", \"code\": \"SZ\"}, \n" +
            "{\"name\": \"blackandwhitephotography\", \"code\": \"SE\"}, \n" +
            "{\"name\": \"blackandwhitefilm\", \"code\": \"CH\"}, \n" +
            "{\"name\": \"blackandwhiteart\", \"code\": \"SY\"}, \n" +
            "{\"name\": \"swagbaby\", \"code\": \"TW\"}, \n" +
            "{\"name\": \"swagstyle\", \"code\": \"TJ\"}, \n" +
            "{\"name\": \"cool\", \"code\": \"TZ\"}, \n" +
            "{\"name\": \"cooldude\", \"code\": \"TH\"}, \n" +
            "{\"name\": \"coolcars\", \"code\": \"TL\"}, \n" +
            "{\"name\": \"naturephotography\", \"code\": \"TG\"}, \n" +
            "{\"name\": \"naturephotographylovers \", \"code\": \"TK\"}, \n" +
            "{\"name\": \"naturephotographyvibes \", \"code\": \"TO\"}, \n" +
            "{\"name\": \"naturephotographyshoutout\", \"code\": \"TT\"}, \n" +
            "{\"name\": \"sea\", \"code\": \"TN\"}, \n" +
            "{\"name\": \"adventure\", \"code\": \"TR\"}, \n" +
            "{\"name\": \"summervibes\", \"code\": \"TM\"}, \n" +
            "{\"name\": \"pink\", \"code\": \"TC\"}, \n" +
            "{\"name\": \"nails\", \"code\": \"TV\"}, \n" +
            "{\"name\": \"pinkaesthetic\", \"code\": \"UG\"}, \n" +
            "{\"name\": \"pinkmakeup\", \"code\": \"UA\"}, \n" +
            "{\"name\": \"black\", \"code\": \"AE\"}, \n" +
            "{\"name\": \"blackowned\", \"code\": \"GB\"}, \n" +
            "{\"name\": \"blackisbeautiful\", \"code\": \"US\"}, \n" +
            "{\"name\": \"petstagram\", \"code\": \"UM\"}, \n" +
            "{\"name\": \"catloversclub\", \"code\": \"UY\"}, \n" +
            "{\"name\": \"lovecats\", \"code\": \"UZ\"}, \n" +
            "{\"name\": \"catstagram\", \"code\": \"VU\"}, \n" +
            "{\"name\": \"bestmeow \", \"code\": \"VE\"}, \n" +
            "{\"name\": \"wanderlustphotography\", \"code\": \"VN\"}, \n" +
            "{\"name\": \"wanderlusttravel\", \"code\": \"VG\"}, \n" +
            "{\"name\": \"wanderlustlife\", \"code\": \"VI\"}, \n" +
            "{\"name\": \"techie\", \"code\": \"WF\"}, \n" +
            "{\"name\": \"techielife\", \"code\": \"EH\"}, \n" +
            "{\"name\": \"gadgetlover\", \"code\": \"YE\"}, \n" +
            "{\"name\": \"techupdates\", \"code\": \"ZM\"}, \n" +
            "{\"name\": \"instatechnology\", \"code\": \"ZW\"} \n" +
            "]";
}
